### ISSUE TITLE
API Version 1.2?

### ISSUE THREAD

**Issue by Gemini2350** [3dmedium/nmos_crosspoint#1]
Hi

Thanks for your great work.
Since there are many audio devices that only use Nmos version 1.2, is there any way to force the nmos-crosspoint to use API version 1.2 (and not 1.3 as the newest) towards the registrar?
Thank you and sorry for using issues for this request

**Comment by 3dmedium** [comment]
Hi @Gemini2350 ,
A lot of newer devices, also for Video, only support NMOS Version 1.2 and 1.3.
In most cases the problem is, dropping support vor version 1.1.
As there are some differences, in some cases there will be some more changes for my tool. I am working on those.

If you are running the nmos-cpp registry, each device will just select its best fitting version. You can change the config or use an older version of nmos-cpp to force the devices using an older version.

Maybe the most simple thing to use devices with different versions is to add them to the versions in the code.

[nmosConnector.ts on line 123](https://github.com/3dmedium/nmos_crosspoint/blob/d4e2c148a0aae558033b5ea23e1189acc89e1f20/server/lib/nmosConnector.ts#L123)
```typescript
    private version = "v1.2";
    private connectVersionList = ["v1.2","v1.1", "v1.0"];
```
You can just add the new version to the list.
For me this works for most of the devices i am testing.

If you still have problems, feel free to give feedback here. Maybe i can help with some more changes and an newer version.

**Comment by 3dmedium** [comment]
In Version 2.0 there are now more possibilities to configure versions.
